### ISSUE TITLE
Bug in Tempate {% for key, value in myarray %} construct

### ISSUE THREAD

**Issue by gibbonweb** [TomFrost/Hydrogen#10]
the {% for key, value in myarray %} throws an exception if key and value are not separated by a space.
i.e.
{% for key, value in myarray %} => works fine
{% for key,value in myarray %} => throws exception

This is very counter-intuitive and just cost me 15min to figure out ...

Don't have time to fix ist myself atm, just leaving it here fyi and might fix it later if I find the time...

**Comment by TomFrost** [comment]
Fixed :).  Thanks for the suggestion!
