### ISSUE TITLE
Count() in loop (StandardSQLFormatter)

### ISSUE THREAD

**Issue by ghost** [TomFrost/Hydrogen#9]
Hey, these are just a couple of tiny things I noticed in /database/formatters/StandardSQLFormatter.php's getPreparedQuery() method while just exploring the Query creation process.

``` PHP
public function getPreparedQuery() {
        $str = '';
        for ($i = 0, $j = count($this->parsed); $i < $j; $i += 2) // instead of count()ing every time.
            $str .= $this->parsed[$i] . '?';
        return substr($str, 0, -1);
    }
```

Or maybe, a viable option could be implode() instead of the loop although I don't know how you'd make it work with the $i += 2.

**Comment by TomFrost** [comment]
Good catch!  Sorry it took me so long to get to this :).  Fixed now, though!
